### ISSUE TITLE
Retroalimentación

### ISSUE THREAD

**Issue by cosmoscalibur** [EduinHSERNA/kaggle-titanic#3]
# Ponderación
- `README.md`: 0,5  
- Instalación: 0,1  
- Inicialización: 0,1  
- Consulta: 0,1  
- Extracción: 1,5  
- Descarga: 1,0
- Consulta: 0,3  
- `LICENSE`: 0,2  
- Markdown: 0,3  

Ponderación total: 4,1
# Retroalimentación
- `Documentación.ipynb`: Los enlaces de secciones de notebooks no son funcionales salvo que se haga uso adecuado del ambiente html `href`. Igualmente, se observa que dichos enlaces no redireccionan a la sección del notebook sino a los `commit`s asociados, por lo cual no da claridad por la convención de corresponder a un contenido. La indicación de los `commit`s con sus implementaciones se lee directo del historial del repositorio o requiere de una redacción clara que indique a lo que apunta el enlace. La documentación se debe centrar en el uso del paquete, a un usuario final no le importa que sabe el desarrollador ni que alternativas existen en medio de la consulta de como usar. Las alternativas se pueden usar como una sección adicional, sin embargo se presenta contradicción ya que finalmente se hace uso de algo que dice no usar.  
  - Instalación: No hay consistencia entre las dependencias de python indicadas y el proceso de instalación. Se indica como dependencia a `jupyter` el cual no se indica su instalación y a un modulo `panda` el cual no existe pero se menciona en la instalación uno llamado `pandas`. Igualmente, en la instalación se menciona la instalación de `request` el cual no esta indicado como dependencia.  
  - Inicialización: La inicialización no depende de instalar siempre por lo cual no se puede asumir un proceso secuencial en los pasos. Si ya esta instalado de algún momento dado y se desea inicializarlo, la indicación del directorio es relativa a otro directorio no mencionado. Carece de reproducibilidad la indicación.  Si el uso del notebook es exclusivo para dicho archivo, podemos usar directamente `jupyter notebook Documentacion.ipynb`. No hay uso de celdas de código para la ilustración de inicialización.  
  - Extracción: Se indico que era parte del bloque de inicialización. La documentación se indico que corresponde a la forma de uso y no sobre la implementación. Al usuario final no le importa que modulos se importan internamente sino lo que él debe importar para la manipulación del paquete desarrollado. La celda de código usada no ilustra el funcionamiento del código.  
  - Consulta: Nuevamente la documentación se corresponde a como usar el paquete y no a que mecanismos adecuados existen que no se vayan a usar ni como se desarrollo la clase (el modulo `panda` no existe). La única sección asociada a la mención del curso era el archivo `README.md` indicando la actividad como requisito de curso. Para un usuario final no le importa lo que vio el desarrollador en clase, le importa como usar el desarrollo. Nuevamente no se ilustro en celdas de código la consulta. Hay contradicción en la documentación, ya que se menciona que no se usará `pandas` porque no fue visto en clase pero luego hasta posee una sección propia.  
- Código: Indica claramente el documento de requisitos que solo podían usarse las funciones vistas a la fecha en que se indico el taller. El equivalente de `pandas` en terminos de las sesiones vistas corresponde a la sesión asociada a R y bases de datos, que es un tema posterior al de extracción web. Contrario a lo que expresa la documentación, numpy si se ha usado previamente en el curso, y por ende ese si era valido (una de las actividades contiene su uso opcional, para el desarrollo de la suma polinomica). La flexibilidad indicada que se comento corresponde a los temas siguientes a la extracción.  
  - Extracción: Se recomienda la posibilidad de incluir el gestor de _cookies_ de `requests` para evitar la repetición del ingreso (en caso de que realmente se este saliendo de sesión continuamente) y mejorar el tiempo de ejecución.
  - Descarga: El módulo shutil es una abstracción multiplataforma con implementaciones que no son a bajo nivel, por lo cual son funciones muy lentas. Se recomienda que el argumento `f` contenga la ruta completa del archivo con el fin de evitar la ejecución de `shutil.move` y usar el método `write` del objeto `f` evitando `shutil.copyfileobj`. En general, `shutil` resulta bastante conveniente para operaciones de sistema multiplataforma.  
  - Consulta: Con lo visto en el archivo `consulta.sh`, aparenta que los rangos numéricos no son de interés sino solo valores exactos, lo cual es inconsistente con la exposición presentada y el objetivo deseado. La función implementada de consulta no genera la visualización adecuada en notebook. El uso de `pandas` no estaba avalado para la consulta ni generación de visualización en notebook por no ser _core_.

**Comment by cosmoscalibur** [comment]
# Entrega 2

## Ponderación

+ Instalación: 0,4/0,5  
+ Estadistica Descriptiva: 0,8/1,2  
+ Estadistica Inferencial: 0,0/1,5  
+ Reporte Estadistico: 0,0/1,0  
+ Correcciones Entrega 1: 0,7/0,8  

Ponderación: 1,9/5,0

## Retroalimentación

+ Instalación:  `R`, `pip` y `jupyter` son paquetes convencionalmente no incluidos en las distribuciones y no se detalla su instalación.  
+ Código:    
    + Estadistica descriptiva: Se presentaron estadisticas descriptivas, pero no las solicitadas.  
    + Estadistica inferencial: Ausencia de avance en la estadistica inferencial.  
    + Reporte estadistico: No se desarrollo código para generación de reporte.  
+ Correcciones Entrega 1:  
    + La instalación de las dependencias preferiblemente debe recomendarse su consulta a los desarrolladores oficiales, de lo contrario la atención a la solución de problemas del paquete propio se verá afectado por la atención de problemas de otros, que no necesariamente estarán al alcance nuestro. Esta indicación de soporte es importante para el paquete propio (recomendación).  
    + Que distinción hay entre las dependencias que aparecen explicitamente como requerimientos y las dependencias que aparecen en la sección de instalación separada. Esto genera confusión y puede dar a entender una relación del desarrollador con los paquetes que se dejaron resaltados con la instalación propia (bs y requests).  
    + La instalación no incluye la ejecución del código, ya que esto no instala nada. Justamente, el funcionamiento del codigo incluye la obtención de datos, pero esto no es instalación sino inicialización.  
    + La inicialización justamente inicia en la obtención de los datos. Por otro lado, es imposible que la inicialización depende del notebook por dos motivos. Si depende de abrir el notebook, sería autoreferente, ya que justamente para leer eso ya esta en el archivo de documentación. Igualmente, el archivo de documentación es justamente documentación, y por ende no es un espacio de ejecución salvo para ejemplificación.  
    + Persiste la ausencia de celdas de código para la ejemplificación y se presento con las pocas celdas que no ilustran funcionamiento sino verificación sin sus salidas.  
    + Se presentaron resultados de ejecución sin ser salida de ejecución de celdas, que era el requerimiento.  
    + Al persistir el uso interactivo del código sh evita su uso en notebook.  
    + No hay generación markdown de las consultas por medio de código.  
    + La consulta y exploración se corresponde a lo mismo. No claridad en que se diferencia la mencipon de _exploración_ en comparación a _consulta_, e igualmente no se corresponde con nada solicitado. No se realizo corrección de la consulta.  
    + Al realizar la descarga, dejar como parte del repositorio los archivos descargados.

**Comment by cosmoscalibur** [comment]
Persiste ausencia de indicación completa de dependencias y se requiere de forma adecuada. La instalación debe ser como administrador.  
Ya presenta resultados de estadistica descriptiva e inferencial, pero se debe trabajar en la presentación del reporte de la información. Particularmente hay ausencia de presentación adecuada en markdown ademas de la poca legibilidad.  
Persisten los pendientes de las correcciones de la entrega 1.  
Ponderación de nota: 3,0/5,0.

**Comment by cosmoscalibur** [comment]
# Entrega 3

No se realizo.

**Comment by EduinHSERNA** [comment]
Se subieron los requerimientos de las imagenes para Gnuplot y en otro
formato.
El cual no a sido calificado en ninguna de las evaluaciones.

*Eduin H SERNA*
Computación Científica.
Universidad de Medellín.
57+ 301 39 08 571

2016-11-11 18:24 GMT-05:00 Edward Yesid Villegas <notifications@github.com>:
